### PR TITLE
Avoid a warning using explicit enumeration value in switch

### PR DESCRIPTION
**Pull request by malaterre**

### CODE REVIEW

**Comment by bgilbert** [comment]
That switch block has a `default` label, so the missing case shouldn't produce a warning.  What compiler version are you using, and what is the warning message?

**Comment by malaterre** [comment]
I used `gcc` with `-Wall -Wextra`. Let try again tonight to get the exact message.

**Comment by bgilbert** [comment]
@malaterre Did you ever find out what was going on?

**Comment by bgilbert** [comment]
Closing as stale.

**Pull request closed without merging**
