### PR TITLE
Support for optra format

### PR DESCRIPTION
**Pull request by surajoptra**
Added optra driver file and modified other files to support optra format images

Signed-off-by: surajoptra <s.somwanshi@optraventures.com>

### CODE REVIEW

**Comment by surajoptra** [comment]
not able to force push, closing this pull request and attempt fresh pull request

**Comment by bgilbert** [comment]
Looks like you added a new commit, rather than updating the existing commit.  Every commit in the PR must be properly signed off.

Also, please use your full name for the commit author name and signoff.

**Comment by surajoptra** [comment]
Hi Benjamin,
I would like to apologize for some close and reopen on issues.
Since I am very new to Github, I am not able to do it in correct way.
I tried closing earlier PR and deleted my fork.
I guess now I will need new PR to proceed?

Best Regards,
Suraj S.

**Comment by bgilbert** [comment]
That's okay, GitHub takes some time to learn.  Yes, now that you've deleted your branch, you'll need to open a new pull request.

**Pull request closed without merging**
