### PR TITLE
Add a tool to query and write associated images.

### PR DESCRIPTION
**Pull request by alex-virodov**
This is part of tooling that I need to implement request https://github.com/openslide/openslide/pull/437#discussion_r1174073883.

Tested:
```
~/openslide/builddir$ tools/openslide-write-associated-images /home/me/Downloads/TCGA-86-A456-01A-01-TSA.996EFBE2-10E2-454B-B4E7-981FA24404B0.svs 
Opening slide: '/home/me/Downloads/TCGA-86-A456-01A-01-TSA.996EFBE2-10E2-454B-B4E7-981FA24404B0.svs'
Listing associated images:
associated image: 'thumbnail'
Done listing.

~/openslide/builddir$ tools/openslide-write-associated-images /home/me/Downloads/TCGA-86-A456-01A-01-TSA.996EFBE2-10E2-454B-B4E7-981FA24404B0.svs thumbnail /home/me/openslide/thumbnail.png
Opening slide: '/home/me/Downloads/TCGA-86-A456-01A-01-TSA.996EFBE2-10E2-454B-B4E7-981FA24404B0.svs'
Extracting associated image: 'thumbnail'
Dimensions: 1024, 217
Writing output file: '/home/me/openslide/thumbnail.png'
```
----
Note: the `openslide_close()` fails for some reason on SIGSEGV, trying to `g_free(osr);`. Is this a known bug? I don't see the openslide-write-png closing the openslide handle either. If I add `openslide_close(osr)` to the sample, I get the same failure:
```
/home/me/openslide/builddir/tools/openslide-write-png /home/me/Downloads/TCGA-86-A456-01A-01-TSA.996EFBE2-10E2-454B-B4E7-981FA24404B0.svs 0 0 3 1000 1000 /home/me/openslide/output.png

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

### CODE REVIEW

**Comment by bgilbert** [comment]
Thanks for the PR!

It feels slightly awkward to have two tools that do almost the same thing, and that share a lot of duplicated code.  From the name of `openslide-write-png`, it'd make sense for that tool to handle associated images as well.  I'd propose adding an `--associated` option to `openslide-write-png`, which would cause it to take an argument list of `slide associated-image output.png`.  Unfortunately that would require some refactoring of `openslide-common-cmdline.c`, since there's currently no way for tools to add additional options to the `GOptionContext`.

As for listing the associated images... I'm torn.  Adding an option to `openslide-show-properties` makes some sense, except that the list of associated images isn't a property.  Adding the option to `openslide-write-png` makes sense to keep the image-related utilities together, except that the list of associated images isn't a PNG.

Interested in your thoughts here.

The crash you're describing is because an explicit `openslide_close(osr)` would cause a double free.  The `openslide_t` is already being closed automatically by the `g_autoptr(openslide_t)`.

**Comment by alex-virodov** [comment]
> Interested in your thoughts here.

My thought is that the proposed structure is the optimal one of course :). More seriously:

The proposed code follows the unix philosophy of "Write programs that do one thing and do it well". This tool handles all aspects of associated images, and does not handle other aspects handled by other tools. So I respectfully disagree with "two tools that do almost the same thing" - they do two very different things imho, just happen to write .pngs in the process.

As to code duplication, the only real code duplication is the 'fail' function and *some* png write logic (as both tools write pngs, but very differently). If there's a place to refactor that code to, I can do the refactor, but I think the write_png function should stay as-is, and only the fail() function should be refactored.

Those are my thoughts. I am happy to continue to discuss, or follow any specific direction you would have.

**Comment by bgilbert** [comment]
OpenSlide is primarily a library.  It's good to provide a command-line tool for exercising it, but I'd rather not keep adding separate small programs for each piece of the API, that downstreams will then need to package.  (One practical problem is that the Windows binaries are now statically linked and cost about 1.5 megabytes each in the zipfile.)

For example, there's recently been some discussion of implementing #139.  Should we add a separate dedicated program just to extract an ICC profile?  It doesn't really fit into any of the existing ones.

So actually, the best approach might be to ship a single program e.g. `openslide-tool` with subcommands like `openslide-tool read-region` and `openslide-tool properties`.  This PR would then add e.g. `openslide-tool associated list` and `openslide-tool associated read`.  The command could also check `argv[0]` and act as the legacy tools if invoked by those names.

If you'd like to work on that, feel free, but I don't expect you to embark on a major refactoring.  We can leave this PR open as a placeholder, and I may try out that approach and see how it feels.  If we're going to make that change, 4.0.0 would be a good time.

In any event, this shouldn't be necessary for #437, so let's keep it independent of that PR.  I usually use OpenSlide Python to test the API.

**Comment by alex-virodov** [comment]
> One practical problem is that .. binaries .. cost about 1.5 megabytes each

I understand completely, and agree with the rest of the points.

> In any event, this shouldn't be necessary for https://github.com/openslide/openslide/pull/437

I will remove it from that branch.

>  I usually use OpenSlide Python to test the API.

FYI one downside of this approach is that you cannot use a C debugger, as you won't have a C entry point. At least not conveniently, afaik (*). Not always needed, but sometimes useful. Maybe an alternative would be to have this program as a testing tool so it won't be shipped.

(*) If you know of a convenient way to debug C code from python entrypoint with CLion, I would be curious to just know that it is possible. My experience is with Java/JNI/C++, and it is not a good one.

**Comment by bgilbert** [comment]
> FYI one downside of this approach is that you cannot use a C debugger, as you won't have a C entry point.

Hmm, works for me:

```
$ gdb python

[elided prompts about debuginfod and loading debuginfo]

(gdb) break openslide_read_associated_image
Function "openslide_read_associated_image" not defined.
Make breakpoint pending on future shared library load? (y or [n]) y
Breakpoint 1 (openslide_read_associated_image) pending.
(gdb) run
Starting program: /usr/bin/python 

[elided debuginfo messages]

Python 3.11.3 (main, Apr  5 2023, 00:00:00) [GCC 13.0.1 20230401 (Red Hat 13.0.1-0)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import openslide

[elided debuginfo messages]

>>> s=openslide.OpenSlide('CMU-1.svs')
>>> s.associated_images['label']

Breakpoint 1, openslide_read_associated_image (osr=0x55555593cd30, 
    name=0x7fffe9fac2c0 "label", dest=0x7fffe879a010) at ../src/openslide.c:572
572	  if (openslide_get_error(osr)) {
(gdb) 
```

**Comment by bgilbert** [comment]
I've implemented the subcommand approach in #465.  It's still a draft, but feels like a good direction to go in.

I'll go ahead and close this PR for now.  Thanks for sending it, and for pointing out the need for this tooling!

**Pull request closed without merging**
